---
- hosts: digitalocean
  tasks:
   - name: Update APT package cache
     action: apt update_cache=yes

   - name: Update APT to the latest packages
     action: apt upgrade=src

   - name: Install nginx web server
     apt: pkg=nginx state=installed update_cache=true
     notify:
      - start nginx

   - name: Upload default index.html for host
     copy: src=static_file/index.html dest=/usr/share/nginx/www/ mode=0644

  handlers:
   - name: start nginx
     service: name=nginx state=started