- name: Generate SSH Keys for deploy user
  user: user=deploy generate_ssh_key=yes ssh_key_bits=2048
  register: deploy

- name: Show SSH Keys
  command: "cat /home/deploy/.ssh/id_rsa.pub"
  register: cat

- debug: msg="{{ cat.stdout }}"

- name: Wait for user to copy ssh key
  pause: prompt="Plase add the SSH public key above to your SCM account"
  register: pause